### ISSUE TITLE
a question about semidominator

### ISSUE THREAD

**Issue by liusy58** [Dmitrryy/SoN#2]
hi, lucky to see your implementation about dominators, I am not sure why `u` can be calculated like this

```
while (uDFS >= vDFS) {
          uDFS = dfsParents[uDFS];
        }
```

Could you please give me an explanation?

**Comment by DragonZoom** [comment]
Thanks for your interest in the implementation. 

The implementation is based on article [A fast algorithm for finding dominators in a flowgraph](https://dl.acm.org/doi/pdf/10.1145/357062.357071).  Useful lemmas and theorems can be found on pages 4-6.

Let me try to explain the part of the algorithm that interests you. 
`DFS` values `u > v` means that during a DFS traversal, vertex `u` was visited later than vertex `v`. In our case, `u` is the ancestor of vertex `v`, therefore there is a path from `START` to `v` that does not contain `u` (this is a path along the DFS spanning tree), therefore `u` cannot be a dominator. A candidate for a dominant vertex is a vertex with a DFS value less than the dominated vertex (we look for such a vertex in a cycle, climbing the DFS spanning tree).

## Example
Example to illustrate how non-tree edges can lead to a node that dominates v but is not its ancestor in the DFS tree, which is directly related to the loop we are interested in.:
```
    A
   / \
  B   C
  | /
  D
  |
  E
```
The DFS tree (composed of tree edges) would look like this:
```
    A
   / \
  B   C
  |
  D
  |
  E
```
In terms of dominance:
- `B` is an ancestor of `D` in the DFS tree and thus a candidate for being a dominator of `D`.
- `C` is not an ancestor of `D` in the DFS tree, but there's a direct path from `C` to `D`.

The path `A -> C -> D` is not included in the DFS tree, but it's crucial for determining the dominators of `D`.  And the loop we are interested in is precisely for finding such a path.

Thus, `A` dominates `D`, even though it is not an ancestor of `D` in the DFS tree. 

I hope I answered your issue. Please write if you have any comments =)

**Comment by liusy58** [comment]
Sorry for my late response, thx a lot!
